{
    'name': 'AGF Cargo',
    'version': '17.0.1.0.0',
    'summary': 'Sistem Manajemen Kargo Tanaman — PT Berkah Melano Indonesia',
    'author': 'K01-G03 IF3141',
    'category': 'Logistics',
    'depends': ['base', 'web', 'portal', 'website'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'views/assets.xml',  
        'views/admin/base_layout.xml',
        'views/admin/admin_dashboard.xml',
        'views/admin/batch.xml', 
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
