#!/usr/bin/env python3
"""
Seed test data for agf_cargo module.

Creates:
  - 1 active batch (keberangkatan 14 hari ke depan)
  - 4 kargo dengan berbagai status
  - Tanaman items per kargo
  - Tahapan log per kargo
  - 4 QR tags (2 aktif, 2 idle)

Usage:
    python3 scripts/seed_test_data.py

Requires: Odoo running at localhost:8069 with admin/admin
"""
import xmlrpc.client
import sys
from datetime import date, timedelta

# ── Config ───────────────────────────────────────────────────────────
URL      = 'http://localhost:8069'
DB       = 'postgres'
USERNAME = 'admin'
PASSWORD = 'admin'
# ─────────────────────────────────────────────────────────────────────

def connect():
    common = xmlrpc.client.ServerProxy(f'{URL}/xmlrpc/2/common')
    uid = common.authenticate(DB, USERNAME, PASSWORD, {})
    if not uid:
        print("❌ Login gagal. Pastikan Odoo berjalan dan kredensial benar.")
        sys.exit(1)
    models = xmlrpc.client.ServerProxy(f'{URL}/xmlrpc/2/object')
    print(f"✅ Login berhasil (uid={uid})")
    return uid, models

def call(models, uid, model, method, args, kwargs=None):
    return models.execute_kw(DB, uid, PASSWORD, model, method, args, kwargs or {})

def create(models, uid, model, vals):
    return call(models, uid, model, 'create', [vals])

def search_read(models, uid, model, domain, fields):
    return call(models, uid, model, 'search_read', [domain], {'fields': fields})

# ─────────────────────────────────────────────────────────────────────

def clear_existing(models, uid):
    """Hapus data test sebelumnya supaya bisa re-run."""
    print("\n🗑  Membersihkan data lama...")
    for model in ['agf.tahapan', 'agf.tanaman.item', 'agf.qr.tag', 'agf.kargo', 'agf.batch']:
        ids = call(models, uid, model, 'search', [[]])
        if ids:
            call(models, uid, model, 'unlink', [ids])
            print(f"   {model}: {len(ids)} record dihapus")

def ensure_admin_group(models, uid):
    """Tambahkan admin ke group_agf_admin supaya punya akses create/write."""
    groups = call(models, uid, 'res.groups', 'search_read',
                  [[('name', '=', 'Admin AGF')]], {'fields': ['id', 'full_name']})
    if not groups:
        print("⚠  Group 'Admin AGF' tidak ditemukan — pastikan agf_cargo terinstall.")
        sys.exit(1)
    group_id = groups[0]['id']
    call(models, uid, 'res.users', 'write',
         [[uid], {'groups_id': [(4, group_id)]}])
    print(f"✅ Admin ditambahkan ke group '{groups[0]['full_name']}'")


def seed(models, uid):
    ensure_admin_group(models, uid)
    today = date.today()
    departure = (today + timedelta(days=14)).isoformat()

    # ── 1. Active batch ──────────────────────────────────────────────
    print("\n📦 Membuat batch aktif...")
    batch_id = create(models, uid, 'agf.batch', {
        'tanggal_keberangkatan': departure,
        'tanggal_mulai': today.isoformat(),
        'status': 'aktif',
        'catatan': 'Batch test data — generated by seed script',
    })
    batch = search_read(models, uid, 'agf.batch', [('id', '=', batch_id)], ['name', 'batch_id'])
    batch_code = batch[0]['batch_id']
    print(f"   Batch ID={batch_id}  kode={batch_code}  berangkat={departure}")

    # ── 2. Kargo records ─────────────────────────────────────────────
    print("\n🌿 Membuat kargo (4 pesanan)...")

    kargo_fixtures = [
        {
            'nama_penitip':    'Budi Santoso',
            'hp_penitip':      '+62 812-3456-7890',
            'email_penitip':   'budi@example.com',
            'alamat_penitip':  'Jl. Merdeka No. 10, Bandung 40111',
            'nama_penerima':   'John Smith',
            'hp_penerima':     '+1 555-234-5678',
            'email_penerima':  'john.smith@email.com',
            'alamat_penerima': '123 Main St, Los Angeles, CA 90001',
            'kota_tujuan':     'Los Angeles',
            'negara_tujuan':   'USA',
            'layanan_lokal':   'reguler',
            'additional_packaging': 'dakron',
            'winter_packaging': 'none',
            'status':          'arrival',
            'batch_id':        batch_id,
            '_tanaman': [
                {'nama_tanaman': 'Monstera deliciosa',  'jumlah': 5,  'ukuran': 'sedang', 'kondisi': 'sehat'},
                {'nama_tanaman': 'Philodendron gloriosum', 'jumlah': 3, 'ukuran': 'kecil', 'kondisi': 'sehat'},
            ],
            '_tahapan': [
                ('01_registrasi',   'Pendaftaran kargo berhasil.',           'Bandung'),
                ('02_penjemputan',  'Tanaman dijemput dari lokasi pengirim.', 'Bandung'),
                ('03_gudang_asal',  'Tanaman diterima di gudang AGF.',        'Parongpong'),
            ],
        },
        {
            'nama_penitip':    'Siti Rahayu',
            'hp_penitip':      '+62 821-9876-5432',
            'email_penitip':   'siti@example.com',
            'alamat_penitip':  'Jl. Sudirman No. 5, Jakarta 10220',
            'nama_penerima':   'Maria Garcia',
            'hp_penerima':     '+1 555-876-5432',
            'email_penerima':  'maria.garcia@email.com',
            'alamat_penerima': '456 Oak Ave, Miami, FL 33101',
            'kota_tujuan':     'Miami',
            'negara_tujuan':   'USA',
            'layanan_lokal':   'next_day',
            'additional_packaging': 'tissue',
            'winter_packaging': 'heat_pack',
            'status':          'processing',
            'batch_id':        batch_id,
            '_tanaman': [
                {'nama_tanaman': 'Anthurium crystallinum', 'jumlah': 2, 'ukuran': 'besar', 'kondisi': 'sehat'},
                {'nama_tanaman': 'Hoya kerrii',            'jumlah': 10, 'ukuran': 'kecil', 'kondisi': 'kurang_sehat'},
                {'nama_tanaman': 'Calathea orbifolia',     'jumlah': 4,  'ukuran': 'sedang', 'kondisi': 'sehat'},
            ],
            '_tahapan': [
                ('01_registrasi',  'Pendaftaran kargo berhasil.', 'Jakarta'),
                ('03_gudang_asal', 'Diterima di gudang.',         'Parongpong'),
                ('04_cek_dokumen', 'Dokumen lengkap dan valid.',  'Parongpong'),
            ],
        },
        {
            'nama_penitip':    'Ahmad Fauzi',
            'hp_penitip':      '+62 813-1111-2222',
            'email_penitip':   'ahmad@example.com',
            'alamat_penitip':  'Jl. Diponegoro No. 20, Surabaya 60241',
            'nama_penerima':   'David Lee',
            'hp_penerima':     '+1 555-111-2222',
            'email_penerima':  'david.lee@email.com',
            'alamat_penerima': '789 Pine Rd, Seattle, WA 98101',
            'kota_tujuan':     'Seattle',
            'negara_tujuan':   'USA',
            'layanan_lokal':   'reguler',
            'additional_packaging': 'none',
            'winter_packaging': 'heat_insulation',
            'status':          'hold',
            'batch_id':        batch_id,
            '_tanaman': [
                {'nama_tanaman': 'Alocasia zebrina', 'jumlah': 6, 'ukuran': 'sedang', 'kondisi': 'belum_dicek'},
            ],
            '_tahapan': [
                ('01_registrasi', 'Menunggu konfirmasi dokumen ekspor.', 'Surabaya'),
            ],
        },
        {
            'nama_penitip':    'Dewi Permata',
            'hp_penitip':      '+62 878-5555-6666',
            'email_penitip':   'dewi@example.com',
            'alamat_penitip':  'Jl. Gatot Subroto No. 99, Denpasar 80361',
            'nama_penerima':   'Sarah Johnson',
            'hp_penerima':     '+1 555-555-6666',
            'email_penerima':  'sarah.j@email.com',
            'alamat_penerima': '321 Elm St, New York, NY 10001',
            'kota_tujuan':     'New York',
            'negara_tujuan':   'USA',
            'layanan_lokal':   'next_day',
            'additional_packaging': 'dakron',
            'winter_packaging': 'insulation',
            'status':          'shipped',
            'batch_id':        batch_id,
            '_tanaman': [
                {'nama_tanaman': 'Begonia maculata',     'jumlah': 8,  'ukuran': 'kecil',  'kondisi': 'sehat'},
                {'nama_tanaman': 'Ficus lyrata',         'jumlah': 2,  'ukuran': 'besar',  'kondisi': 'sehat'},
                {'nama_tanaman': 'Pothos golden',        'jumlah': 15, 'ukuran': 'kecil',  'kondisi': 'sehat'},
            ],
            '_tahapan': [
                ('01_registrasi',      'Pendaftaran kargo berhasil.',             'Denpasar'),
                ('03_gudang_asal',     'Diterima di gudang AGF.',                 'Parongpong'),
                ('04_cek_dokumen',     'Semua dokumen lengkap.',                  'Parongpong'),
                ('05_terminal_asal',   'Tanaman tiba di terminal kargo.',         'Jakarta'),
                ('06_transit',         'Dalam perjalanan ke negara tujuan.',      'In-flight'),
                ('07_terminal_tujuan', 'Tiba di terminal kargo tujuan.',          'New York JFK'),
                ('08_bea_cukai',       'Lolos pemeriksaan bea cukai & USDA.',    'New York JFK'),
                ('10_pengiriman',      'Dalam pengiriman lokal ke alamat penerima.', 'New York'),
            ],
        },
    ]

    kargo_ids = []
    for fixture in kargo_fixtures:
        tanaman_data = fixture.pop('_tanaman')
        tahapan_data = fixture.pop('_tahapan')

        kargo_id = create(models, uid, 'agf.kargo', fixture)
        kargo = search_read(models, uid, 'agf.kargo', [('id', '=', kargo_id)],
                            ['nomor_penitip', 'nomor_penerima'])
        nomor_p = kargo[0]['nomor_penitip']
        nomor_r = kargo[0]['nomor_penerima']
        print(f"   Kargo {nomor_p} / {nomor_r}  ({fixture['status']})")

        # Tanaman items
        for t in tanaman_data:
            t['kargo_id'] = kargo_id
            create(models, uid, 'agf.tanaman.item', t)

        # Tahapan log
        for tahap_code, catatan, lokasi in tahapan_data:
            create(models, uid, 'agf.tahapan', {
                'kargo_id': kargo_id,
                'tahap':    tahap_code,
                'catatan':  catatan,
                'lokasi':   lokasi,
                'cek_daun': tahap_code in ('03_gudang_asal', '10_pengiriman'),
                'cek_akar': tahap_code in ('03_gudang_asal',),
                'cek_hama': tahap_code in ('03_gudang_asal', '04_cek_dokumen'),
            })

        kargo_ids.append(kargo_id)

    # ── 3. QR Tags ───────────────────────────────────────────────────
    print("\n🏷  Membuat QR tags...")
    qr_fixtures = [
        {'status': 'aktif', 'kargo_id': kargo_ids[0]},
        {'status': 'aktif', 'kargo_id': kargo_ids[1]},
        {'status': 'idle',  'kargo_id': False},
        {'status': 'idle',  'kargo_id': False},
        {'status': 'rusak', 'kargo_id': False},
    ]
    for i, qr in enumerate(qr_fixtures, 1):
        tag_id = f'QR-{batch_code}-{i:04d}'
        vals = {
            'tag_id':   tag_id,
            'status':   qr['status'],
            'batch_id': batch_id,
        }
        if qr['kargo_id']:
            vals['kargo_id'] = qr['kargo_id']
        create(models, uid, 'agf.qr.tag', vals)
        print(f"   {tag_id}  ({qr['status']})")

    # ── Summary ──────────────────────────────────────────────────────
    batch_info = search_read(models, uid, 'agf.batch', [('id', '=', batch_id)],
                             ['name', 'total_pesanan', 'total_tanaman'])
    b = batch_info[0]
    print(f"""
✅ Selesai! Data test siap.

   Batch    : {b['name']}  (keberangkatan {departure})
   Pesanan  : {b['total_pesanan']}  (hold / arrival / processing / shipped)
   Tanaman  : {b['total_tanaman']} pcs total
   QR Tags  : 2 aktif, 2 idle, 1 rusak

🌐 Buka di browser:
   Warehouse : http://localhost:8069/agf/warehouse
   Login     : admin / admin
""")

if __name__ == '__main__':
    uid, models = connect()

    if '--fresh' in sys.argv:
        clear_existing(models, uid)
    elif len(sys.argv) > 1 and sys.argv[1] != '--fresh':
        print("Usage: python3 scripts/seed_test_data.py [--fresh]")
        print("  --fresh  hapus semua data lama sebelum seed")
        sys.exit(0)

    seed(models, uid)
